services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "127.0.0.1:1883:1883"
    volumes:
      - ./mosquitto-config:/mosquitto/config
      - ./mosquitto-data:/mosquitto/data
      - ./mosquitto-log:/mosquitto/log

  ring-mqtt:
    image: tsightler/ring-mqtt
    container_name: ring-mqtt
    restart: unless-stopped
    depends_on:
      - mosquitto
    ports:
      - "127.0.0.1:8554:8554"
    volumes:
      - ./ring-mqtt-data:/data